name: trading-backtest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.23.5
  - pandas=1.5.3
  - matplotlib=3.6.3
  - seaborn=0.12.2
  - scikit-learn=1.2.2
  - tensorflow=2.11.0
  - gym=0.26.2
  - ccxt=2.9.14
  - yfinance=0.2.18
  - backtrader=1.9.76.123
  - zipline-reloaded=2.4.0
  - requests=2.28.2
